import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "..", "guest.html");
const dist = resolve(here, "..", "dist", "guest.html");
const rust = resolve(here, "..", "..", "backend", "src", "guest_html.rs");

mkdirSync(dirname(dist), { recursive: true });
copyFileSync(source, dist);
writeFileSync(
	rust,
	"// Generated by apps-store/rooms/ui/scripts/build-guest.mjs.\n" +
		'pub const GUEST_HTML: &str = include_str!("../../ui/guest.html");\n'
);
